name: RailDriver
main: ca.mcpnet.RailDriver.RailDriver
version: 0.0.1
commands:
   rd_stock:
      description: stock the player inventory with all required blocks for building a raildriver
      permission: <plugin name>.rd_stock
      usage: <command>
   rd_devkit:
      description: stock the player inventory with a developers kit of tools
      permission: <plugin name>.rd_devkit
      usage: <command> [player]
   rd_cavern:
      description: carve out a cavern from where the player is standing
      permission: <plugin name>.rd_cavern
      usage: <command> size [player]